feat: Formal Verification attributes inside the SSA
blocksense-network/noir pull request #101
Opened 2024-11-06 13:37 UTC by Syndamia

The code compiles, however it needs to be tested.

2024-11-06 14:11 UTC, Aristotelis2002 requested changes

2024-11-06 14:11 UTC, Aristotelis2002 commented on compiler/noirc_frontend/src/monomorphization/ast.rs
> +    pub formal_verification_expressions: Vec<Expression>,
The way you have implemented it we are losing information if the `Expression` is for an ensures attribute or a require attribute. You should create an enum like the ResolvedFvAttribute which contains ensure/requires and their expressions

2024-11-06 14:11 UTC, Aristotelis2002 commented on compiler/noirc_frontend/src/monomorphization/ast.rs
> +    pub formal_verification_expressions: Vec<Expression>,
Also clear on line 10 the unused imports.

2024-11-07 09:27 UTC, Aristotelis2002 approved these changes
LGTM. Please merge after finishing the offline testing.

2024-11-08 08:59 UTC, Aristotelis2002 approved these changes
LGTM. Good documentation

2024-11-08 13:53 UTC, Aristotelis2002 approved these changes
LGTM.

2024-11-11 13:39 UTC, Syndamia commented
To use this branch, you'll need to make some slight modifications, mainly turn off function inlining and force-enable formal verifications.

Inside `compiler/noirc_evaluator/src/ssa.rs` remove lines containing

```rust
.run_pass(Ssa::inline_functions[...], "After inlining:")
```

Inside `compiler/noirc_frontend/src/hir/mod.rs` change from `false` to `true` the `perform_formal_verification` values.

2024-11-11 13:40 UTC, Aristotelis2002 approved these changes
LGTM.

2024-11-11 13:40 UTC, merged